### ISSUE TITLE
improvements /  TODO's

### ISSUE THREAD

**Issue by diveshuttam** [dashohoxha/egpg#91]
- [ ] Make GUI prettier (taking help from GUI description and #74 )
- [ ] update `GUIdescription.md` after the basic GUI is complete.  
- [ ] TODO's in #90 
- [ ] [comment on pr 69](https://github.com/EasyGnuPG/egpg/pull/69#issuecomment-406882382)
- [ ] update man page
- [ ] update wiki pages
